-- Live Postgres verification. All fixtures are rolled back.
begin;
create temporary table gateway_check_results(check_name text,passed boolean);
do $$
declare u uuid;p uuid;r jsonb;a uuid;b uuid;n integer;s public.ling_gateway_providers;
begin
 update public.ling_gateway_settings set public_enabled=true,owner_reserve=10;
 insert into public.ling_gateway_users(name,role,daily_limit) values('__db_test','user',10) returning id into u;
 r:=public.ling_gateway_reserve(u,'fast');a:=(r->>'id')::uuid;
 if a is null then raise exception 'reserve failed';end if;
 r:=public.ling_gateway_reserve(u,'fast');b:=(r->>'id')::uuid;
 r:=public.ling_gateway_reserve(u,'fast');
 if r->>'error'<>'concurrency_limit' then raise exception 'concurrency guard failed';end if;
 insert into gateway_check_results values('concurrent request reservation cap',true);
 perform public.ling_gateway_finish(a,'failed','[]');perform public.ling_gateway_finish(a,'failed','[]');perform public.ling_gateway_finish(b,'failed','[]');
 select requests into n from public.ling_gateway_usage where user_id=u;
 if n<>0 then raise exception 'refund idempotence failed';end if;
 insert into gateway_check_results values('failed request refund is idempotent',true);
 update public.ling_gateway_users set daily_limit=1 where id=u;
 r:=public.ling_gateway_reserve(u,'fast');a:=(r->>'id')::uuid;
 perform public.ling_gateway_finish(a,'success','[]');r:=public.ling_gateway_reserve(u,'fast');
 if r->>'error'<>'daily_quota_exceeded' then raise exception 'daily guard failed';end if;
 insert into gateway_check_results values('daily quota blocks at exact limit',true);
 insert into public.ling_gateway_providers(name,kind,base_url,enabled,daily_limit,rpm_limit) values('__db_test','custom','https://example.org/v1',true,20,100) returning id into p;
 for n in 1..10 loop if not public.ling_gateway_claim(p,false) then raise exception 'ordinary quota early reject';end if;end loop;
 if public.ling_gateway_claim(p,false) then raise exception 'owner reserve bypassed';end if;
 if not public.ling_gateway_claim(p,true) then raise exception 'owner reserve inaccessible';end if;
 insert into gateway_check_results values('owner capacity reserved from ordinary users',true);
 perform public.ling_gateway_provider_result(p,500,20,false);
 perform public.ling_gateway_provider_result(p,500,20,false);
 perform public.ling_gateway_provider_result(p,500,20,false);
 select * into s from public.ling_gateway_providers where id=p;
 if s.open_until is null or s.open_until<=now() or public.ling_gateway_claim(p,true) then raise exception 'circuit not open';end if;
 insert into gateway_check_results values('three failures open circuit',true);
 update public.ling_gateway_providers set open_until=now()-interval '1 second' where id=p;
 if not public.ling_gateway_claim(p,true) or public.ling_gateway_claim(p,true) then raise exception 'half-open lease failed';end if;
 perform public.ling_gateway_provider_result(p,200,20,true);
 select * into s from public.ling_gateway_providers where id=p;
 if s.open_until is not null or s.probe_until is not null or s.failures<>0 then raise exception 'circuit recovery failed';end if;
 insert into gateway_check_results values('one half-open probe and successful recovery',true);
 update public.ling_gateway_providers set rpm_limit=1 where id=p;
 if public.ling_gateway_claim(p,true) then raise exception 'rpm exceeded';end if;
 insert into gateway_check_results values('provider minute limit enforced',true);
 if exists(select 1 from information_schema.role_table_grants where grantee in ('anon','authenticated') and table_name like 'ling_gateway_%') then raise exception 'public table grants';end if;
 if exists(select 1 from pg_proc join pg_namespace ns on ns.oid=pronamespace where ns.nspname='public' and proname like 'ling_gateway_%' and (has_function_privilege('anon',pg_proc.oid,'execute') or has_function_privilege('authenticated',pg_proc.oid,'execute'))) then raise exception 'public RPC grants';end if;
 insert into gateway_check_results values('anon/authenticated denied tables and RPCs',true);
end $$;
select * from gateway_check_results;
rollback;
