import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createGateway,digest,randomKey,seal,unseal,validBase} from '../src/gateway.mjs';
async function fixture(fetcher,role='admin') {
 const token=randomKey(),keyHash=await digest(token),secret=randomKey(),cipher=await seal(randomKey(),secret);
 const providers=[1,2,3].map(n=>({id:'provider-'+n,name:'test-'+n,enabled:true,kind:'custom',base_url:'https://p'+n+'.example.org/v1',secret_cipher:cipher,aliases:{fast:'upstream-'+n},priority:n}));
 const records=[],results=[],claims=[];
 const user={id:'user-1',role,enabled:true};
 const db={async table(name,query=''){if(name==='keys')return query.includes(keyHash)?[{id:'key-1',user_id:user.id,admin_access:false,enabled:true}]:[];if(name==='users')return[user];if(name==='settings')return[{public_enabled:true,max_output_tokens:4096}];if(name==='providers')return providers;return[];},async rpc(name,args){if(name==='reserve')return{id:'log-1'};if(name==='claim'){claims.push(args);return true;}if(name==='finish'){records.push(args);return;}if(name==='provider_result'){results.push(args);return;}}};
 const gateway=createGateway({SUPABASE_SERVICE_ROLE_KEY:secret},{db,fetcher,firstTimeout:25});
 const req=(body={model:'fast',messages:[{role:'user',content:'hi'}]},t=token,path='/v1/chat/completions')=>new Request('https://gateway.example.org'+path,{method:path.endsWith('models')?'GET':'POST',headers:{authorization:'Bearer '+t,'content-type':'application/json'},body:path.endsWith('models')?undefined:JSON.stringify(body)});
 return {gateway,req,db,records,results,providers,claims};
}
const completion=()=>new Response(JSON.stringify({id:'chat-test',object:'chat.completion',choices:[{index:0,message:{role:'assistant',content:'hello'},finish_reason:'stop'}],usage:{prompt_tokens:2,completion_tokens:1}}),{headers:{'content-type':'application/json'}});
test('API keys authenticate; model aliases stay stable',async()=>{const f=await fixture(()=>completion());assert.equal((await f.gateway(f.req(undefined,'bad','/v1/models'))).status,401);const r=await f.gateway(f.req(undefined,undefined,'/v1/models'));assert.deepEqual((await r.json()).data.map(m=>m.id),['fast','smart','rp','backup']);});
test('application API key cannot enter admin console',async()=>{const f=await fixture(()=>completion());const r=await f.gateway(f.req({},undefined,'/admin/overview'));assert.equal(r.status,401);});
test('Supabase full and stripped function paths work',async()=>{const f=await fixture(()=>completion());for(const prefix of ['/functions/v1/ling-ai-gateway','/ling-ai-gateway']){const r=await f.gateway(f.req(undefined,undefined,prefix+'/v1/models'));assert.equal(r.status,200);}});
test('429 retries second provider and records both attempts',async()=>{let calls=0;const f=await fixture(async()=>++calls===1?new Response('{}',{status:429,headers:{'retry-after':'90'}}):completion());const r=await f.gateway(f.req());assert.equal(r.status,200);assert.equal((await r.json()).model,'fast');assert.equal(calls,2);assert.equal(f.results[0].p_retry,90);assert.deepEqual(f.records[0].p_attempts.map(a=>a.status),[429,200]);});
test('5xx and timeout both fall through to third provider',async()=>{let calls=0;const f=await fixture(async(_u,o)=>{calls++;if(calls===1)return new Response('{}',{status:503});if(calls===2)return new Promise((_,reject)=>o.signal.addEventListener('abort',()=>reject(new Error('timeout'))));return completion();});assert.equal((await f.gateway(f.req())).status,200);assert.equal(calls,3);assert.deepEqual(f.records[0].p_attempts.map(a=>a.status),[503,0,200]);});
test('upstream 400 is not silently retried',async()=>{let calls=0;const f=await fixture(async()=>{calls++;return new Response('{}',{status:400});});assert.equal((await f.gateway(f.req())).status,400);assert.equal(calls,1);assert.equal(f.records[0].p_status,'failed');});
test('failed request settles once and requests refund',async()=>{const f=await fixture(async()=>new Response('{}',{status:500}));assert.equal((await f.gateway(f.req())).status,503);assert.equal(f.records.length,1);assert.equal(f.records[0].p_status,'failed');});
test('malformed 200 JSON is retried',async()=>{let calls=0;const f=await fixture(async()=>++calls===1?new Response('{}'):completion());assert.equal((await f.gateway(f.req())).status,200);assert.equal(calls,2);});
test('closed circuits are skipped without upstream traffic',async()=>{let calls=0;const f=await fixture(async()=>{calls++;return completion();});f.db.rpc=async(name,args)=>name==='reserve'?{id:'log-1'}:name==='claim'?args.p_provider==='provider-2':undefined;assert.equal((await f.gateway(f.req())).status,200);assert.equal(calls,1);});
test('quota rejection prevents all upstream calls',async()=>{let calls=0;const f=await fixture(async()=>{calls++;return completion();});f.db.rpc=async()=>({error:'daily_quota_exceeded'});assert.equal((await f.gateway(f.req())).status,429);assert.equal(calls,0);});
test('stream is rewritten to alias and settles after DONE',async()=>{const f=await fixture(async()=>new Response('data: '+JSON.stringify({id:'a',object:'chat.completion.chunk',model:'real',choices:[{index:0,delta:{content:'hello'}}]})+'\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}}));const r=await f.gateway(f.req({model:'fast',messages:[{role:'user',content:'hi'}],stream:true}));const s=await r.text();assert.ok(s.includes('"model":"fast"'));assert.ok(s.includes('[DONE]'));assert.equal(f.records[0].p_status,'success');});
test('SSE error before first chunk retries',async()=>{let n=0;const f=await fixture(async()=>{n++;return new Response(n===1?'data: {"error":{"message":"bad"}}\n\n':'data: {"choices":[{"delta":{"content":"ok"}}]}\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});});const r=await f.gateway(f.req({model:'fast',messages:[{role:'user',content:'hi'}],stream:true}));assert.ok((await r.text()).includes('ok'));assert.equal(n,2);});
test('truncated stream does not repeat a partially delivered answer',async()=>{let n=0;const f=await fixture(async()=>{n++;return new Response('data: {"choices":[{"delta":{"content":"partial"}}]}\n\n',{headers:{'content-type':'text/event-stream'}});});const r=await f.gateway(f.req({model:'fast',messages:[{role:'user',content:'hi'}],stream:true}));const s=await r.text();assert.ok(s.includes('partial'));assert.ok(s.includes('stream_interrupted'));assert.equal(n,1);assert.equal(f.records[0].p_status,'partial');});
test('SSRF and credential-in-URL inputs are rejected',()=>{for(const url of ['http://x.example.org','https://localhost','https://127.0.0.1/v1','https://user:pass@example.org/v1','https://metadata.internal/v1','https://[::1]/v1','https://example.org:444/v1'])assert.throws(()=>validBase(url));assert.equal(validBase('https://api.example.org/v1/'),'https://api.example.org/v1');});
test('AES ciphertext cannot be decrypted under another server key',async()=>{const c=await seal('secret',randomKey());assert.notEqual(c.data,'secret');await assert.rejects(()=>unseal(c,randomKey()));});
test('invalid model and oversized output never consume quota',async()=>{const f=await fixture(()=>completion());assert.equal((await f.gateway(f.req({model:'wrong',messages:[{role:'user',content:'hi'}]}))).status,400);assert.equal((await f.gateway(f.req({model:'fast',messages:[{role:'user',content:'hi'}],max_tokens:99999}))).status,400);assert.equal(f.records.length,0);});
test('Workers AI monitor uses native model-search endpoint and cannot access administration',async()=>{
 const secret=randomKey(),monitor=randomKey(),key=await seal(randomKey(),secret);let endpoint;
 const db={async table(name){if(name==='settings')return[{monitor_hash:await digest(monitor)}];if(name==='providers')return[{id:'cf',kind:'cloudflare',base_url:'https://api.cloudflare.com/client/v4/accounts/'+'a'.repeat(32)+'/ai/v1',secret_cipher:key}];return[];},async rpc(){}};
 const gateway=createGateway({SUPABASE_SERVICE_ROLE_KEY:secret},{db,fetcher:async url=>{endpoint=url;return Response.json({success:true,result:[]});}});
 const r=await gateway(new Request('https://gateway.example.org/internal/health',{method:'POST',headers:{authorization:'Bearer '+monitor}}));
 assert.equal(r.status,200);assert.ok(endpoint.endsWith('/ai/models/search?per_page=1'));
 const denied=await gateway(new Request('https://gateway.example.org/admin/overview',{headers:{authorization:'Bearer '+monitor}}));assert.equal(denied.status,401);
});
